FROM mambaorg/micromamba:1.5.1

ENV PATH=/opt/conda/bin:$PATH \
    PYTHONUNBUFFERED=1

USER root
RUN apt-get update && apt-get install -y git && rm -rf /var/lib/{apt,dpkg,cache,log}
USER $MAMBA_USER

RUN micromamba install -y -n base -c conda-forge python=3.12 xorg-libxrender && \
    micromamba clean --all --yes

COPY --chown=$MAMBA_USER:$MAMBA_USER . /opt/admet_ai
WORKDIR /opt/admet_ai

RUN /opt/conda/bin/python -m pip install -e . && \
    /opt/conda/bin/python -m pip install "setuptools<81" openpyxl requests fuzzywuzzy "huggingface_hub<1.0" && \
    /opt/conda/bin/python -m pip install PyTDC==1.1.15 --no-deps && \
    /opt/conda/bin/python -m pip cache purge

CMD ["bash"]
